# Generated by Django 2.0.1 on 2018-01-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500)),
                ('opcion1', models.CharField(max_length=20)),
                ('opcion2', models.CharField(max_length=20)),
                ('opcion3', models.CharField(max_length=20)),
                ('opcion4', models.CharField(max_length=20)),
                ('respuesta', models.CharField(max_length=20)),
            ],
        ),
    ]
