# Generated by Django 2.0.1 on 2018-02-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_preguntas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demarcacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_arqueros', models.PositiveIntegerField()),
                ('cantidad_defensas', models.PositiveIntegerField()),
                ('cantidad_centrocampistas', models.PositiveIntegerField()),
                ('cantidad_delanteros', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ataque', models.PositiveIntegerField()),
                ('defensa', models.PositiveIntegerField()),
                ('velocidad', models.PositiveIntegerField()),
                ('demarcacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Demarcacion', to='home.Demarcacion')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='home.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionEquipoIdeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ataque', models.FloatField()),
                ('defensa', models.FloatField()),
                ('velocidad', models.FloatField()),
                ('total', models.FloatField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionPolla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField()),
                ('eq_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_local', to='home.Equipo')),
                ('eq_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_visita', to='home.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Polla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.PositiveIntegerField()),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ParticipacionPolla')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('tipo', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='participacionpolla',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Usuario'),
        ),
        migrations.AddField(
            model_name='participacionequipoideal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Usuario'),
        ),
    ]
