# Generated by Django 2.0.1 on 2018-02-03 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180203_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='modo',
        ),
        migrations.AddField(
            model_name='juego',
            name='n_jugadores',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juego',
            name='tipo',
            field=models.CharField(choices=[('Polla', 'Polla'), ('Trivia', 'Trivia'), ('Equipo', 'Equipo Ideal')], default='Polla', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participacionequipoideal',
            name='juego',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Juego'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participacionpolla',
            name='juego',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Juego'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polla',
            name='juego',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Juego'),
            preserve_default=False,
        ),
    ]
