# Generated by Django 2.0.1 on 2018-02-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180203_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
