# Generated by Django 2.0.1 on 2018-02-04 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180204_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacionpolla',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),

        migrations.AddField(
            model_name='juego',
            name='estado',
            field=models.CharField(blank=True, choices=[('Cerrado', 'Cerrado'), ('Abierto', 'Abierto')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='n',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='privacidad',
            field=models.CharField(blank=True, choices=[('Privado', 'Privado'), ('Publico', 'Publico')], max_length=15, null=True),
        ),
    ]
