# Generated by Django 2.0.1 on 2018-02-06 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_auto_20180204_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacionTrivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Juego')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Juego')),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ParticipacionTrivia')),
                ('preguntas', models.ManyToManyField(to='home.Preguntas')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='participacionpolla',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
