# Generated by Django 2.0.1 on 2018-02-12 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_balancemonetario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancemonetario',
            name='id',
        ),


        
        migrations.AlterField(
            model_name='balancemonetario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
