# Generated by Django 2.0.1 on 2018-02-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_balancemonetario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participacionequipoideal',
            old_name='total',
            new_name='score',
        ),
    ]
