# Generated by Django 2.0.1 on 2018-02-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180211_1949'),
    ]

    operations = [
    
    ]
