# Generated by Django 2.0.1 on 2018-02-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180211_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='estado',
            field=models.CharField(blank=True, choices=[('Cerrado', 'Cerrado'), ('Abierto', 'Abierto')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='privacidad',
            field=models.CharField(blank=True, choices=[('Publico', 'Publico'), ('Privado', 'Privado')], max_length=15, null=True),
        ),
    ]
