# Generated by Django 2.0.1 on 2018-02-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180211_2025'),
    ]

    operations = [
        
    ]
