# Generated by Django 2.0.1 on 2018-02-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180211_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='privacidad',
            field=models.CharField(blank=True, choices=[('Privado', 'Privado'), ('Publico', 'Publico')], max_length=15, null=True),
        ),
    ]
