# Generated by Django 2.0.1 on 2018-02-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180211_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='costo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='juego',
            name='pozo',
            field=models.FloatField(default=0.0),
        ),

        
    ]
