# Generated by Django 2.0.1 on 2018-02-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180211_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='n',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='estado',
            field=models.CharField(blank=True, choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='privacidad',
            field=models.CharField(blank=True, choices=[('Publico', 'Publico'), ('Privado', 'Privado')], max_length=15, null=True),
        ),
    ]
