# Generated by Django 2.0.1 on 2018-02-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180212_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacionequipoideal',
            name='total',
            field=models.FloatField(),
        ),

    ]
