# Generated by Django 2.0.1 on 2018-02-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180212_0040'),
    ]
