# Generated by Django 2.0.1 on 2018-02-22 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180212_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntasTrivia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Juego')),
                ('preguntas_juego', models.ManyToManyField(to='home.Preguntas')),
            ],
        ),
        
    ]
