# Generated by Django 2.0.1 on 2018-02-22 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20180221_2357'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='preguntastrivia',
            name='id',
        ),
        migrations.AlterField(
            model_name='juego',
            name='estado',
            field=models.CharField(blank=True, choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='preguntastrivia',
            name='juego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.Juego'),
        ),
    ]
